/* tslint:disable */
/* eslint-disable */
/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/attendance-api';
export * from './api/custom-tables-api';
export * from './api/documents-api';
export * from './api/metadata-api';
export * from './api/objects-api';
export * from './api/onboarding-api';
export * from './api/payroll-api';
export * from './api/people-api';
export * from './api/reports-api';
export * from './api/tables-api';
export * from './api/tasks-api';
export * from './api/time-off-api';

