/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AttendanceApi,
  CustomTablesApi,
  DocumentsApi,
  MetadataApi,
  ObjectsApi,
  OnboardingApi,
  PayrollApi,
  PeopleApi,
  ReportsApi,
  TablesApi,
  TasksApi,
  TimeOffApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { HiBobCustom } from "./client-custom";

export class HiBob extends HiBobCustom {
  readonly attendance: AttendanceApi;
  readonly customTables: CustomTablesApi;
  readonly documents: DocumentsApi;
  readonly metadata: MetadataApi;
  readonly objects: ObjectsApi;
  readonly onboarding: OnboardingApi;
  readonly payroll: PayrollApi;
  readonly people: PeopleApi;
  readonly reports: ReportsApi;
  readonly tables: TablesApi;
  readonly tasks: TasksApi;
  readonly timeOff: TimeOffApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.attendance = new AttendanceApi(configuration);
    this.customTables = new CustomTablesApi(configuration);
    this.documents = new DocumentsApi(configuration);
    this.metadata = new MetadataApi(configuration);
    this.objects = new ObjectsApi(configuration);
    this.onboarding = new OnboardingApi(configuration);
    this.payroll = new PayrollApi(configuration);
    this.people = new PeopleApi(configuration);
    this.reports = new ReportsApi(configuration);
    this.tables = new TablesApi(configuration);
    this.tasks = new TasksApi(configuration);
    this.timeOff = new TimeOffApi(configuration);
  }

}
