/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AboutPart
 */
export interface AboutPart {
    /**
     * Image URL of the employee\'s avatar.
     * @type {string}
     * @memberof AboutPart
     */
    'avatar'?: string;
    /**
     * An array of the employee\'s hobbies.
     * @type {Array<string>}
     * @memberof AboutPart
     */
    'hobbies'?: Array<string>;
}

