/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AdjustmentRequest
 */
export interface AdjustmentRequest {
    /**
     * Adjustment type - balance or time used.
     * @type {string}
     * @memberof AdjustmentRequest
     */
    'adjustmentType'?: AdjustmentRequestAdjustmentTypeEnum;
    /**
     * Policy type name.
     * @type {string}
     * @memberof AdjustmentRequest
     */
    'policyType'?: string;
    /**
     * The date this adjustment becomes effective.
     * @type {string}
     * @memberof AdjustmentRequest
     */
    'effectiveDate'?: string;
    /**
     * The amount of days/hours to add/subtract.
     * @type {number}
     * @memberof AdjustmentRequest
     */
    'amount'?: number;
    /**
     * A reason for this adjustment.
     * @type {string}
     * @memberof AdjustmentRequest
     */
    'reason'?: string;
}

type AdjustmentRequestAdjustmentTypeEnum = 'balance' | 'daysUsed'


