/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateEmployeeRequestWork } from './create-employee-request-work';

/**
 * 
 * @export
 * @interface CreateEmployeeRequest
 */
export interface CreateEmployeeRequest {
    /**
     * Employee\'s first name.
     * @type {string}
     * @memberof CreateEmployeeRequest
     */
    'firstName': string;
    /**
     * Employee\'s surname.
     * @type {string}
     * @memberof CreateEmployeeRequest
     */
    'surname': string;
    /**
     * Employee\'s email address.
     * @type {string}
     * @memberof CreateEmployeeRequest
     */
    'email': string;
    /**
     * 
     * @type {CreateEmployeeRequestWork}
     * @memberof CreateEmployeeRequest
     */
    'work'?: CreateEmployeeRequestWork;
}

