/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateFieldRequest
 */
export interface CreateFieldRequest {
    /**
     * The description of the field.
     * @type {string}
     * @memberof CreateFieldRequest
     */
    'description'?: string;
    /**
     * The name of the field.
     * @type {string}
     * @memberof CreateFieldRequest
     */
    'name': string;
    /**
     * The category of the field.
     * @type {string}
     * @memberof CreateFieldRequest
     */
    'category': string;
    /**
     * The type of field. Supported field types: text, text-area, number, date, list, multi-list, hierarchy-list, currency, employee-reference, document.
     * @type {string}
     * @memberof CreateFieldRequest
     */
    'type': string;
    /**
     * When true, this field keeps the history of its values, each being active starting from a certain date. The default value is false.
     * @type {string}
     * @memberof CreateFieldRequest
     */
    'historical'?: string;
}

