/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FieldTypeData } from './field-type-data';

/**
 * 
 * @export
 * @interface CustomTableColumn
 */
export interface CustomTableColumn {
    /**
     * The description of the column
     * @type {string}
     * @memberof CustomTableColumn
     */
    'description'?: string;
    /**
     * The ID of the column
     * @type {string}
     * @memberof CustomTableColumn
     */
    'id'?: string;
    /**
     * The name of the column
     * @type {string}
     * @memberof CustomTableColumn
     */
    'name'?: string;
    /**
     * Flag which means that column must be present during creation and its value can\'t be null during update
     * @type {boolean}
     * @memberof CustomTableColumn
     */
    'mandatory'?: boolean;
    /**
     * The type of the column. Supported column types: text, text-area, number, date, list, multi-list, hierarchy-list, currency, employee-reference, document.
     * @type {string}
     * @memberof CustomTableColumn
     */
    'type'?: string;
    /**
     * 
     * @type {FieldTypeData}
     * @memberof CustomTableColumn
     */
    'typeData'?: FieldTypeData;
}

