/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomTableMetadata } from './custom-table-metadata';

/**
 * 
 * @export
 * @interface CustomTableMetadataList
 */
export interface CustomTableMetadataList {
    /**
     * 
     * @type {Array<CustomTableMetadata>}
     * @memberof CustomTableMetadataList
     */
    'tables'?: Array<CustomTableMetadata>;
}

