/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomTableColumn } from './custom-table-column';

/**
 * 
 * @export
 * @interface CustomTableMetadata
 */
export interface CustomTableMetadata {
    /**
     * The description of custom table
     * @type {string}
     * @memberof CustomTableMetadata
     */
    'description'?: string;
    /**
     * The identifier of custom table
     * @type {string}
     * @memberof CustomTableMetadata
     */
    'id'?: string;
    /**
     * The ID of the category to which the custom table belongs
     * @type {string}
     * @memberof CustomTableMetadata
     */
    'category'?: string;
    /**
     * The name of custom table
     * @type {string}
     * @memberof CustomTableMetadata
     */
    'name'?: string;
    /**
     * 
     * @type {Array<CustomTableColumn>}
     * @memberof CustomTableMetadata
     */
    'columns'?: Array<CustomTableColumn>;
}

