/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeProfile } from './employee-profile';

/**
 * 
 * @export
 * @interface EmployeesProfiles
 */
export interface EmployeesProfiles {
    /**
     * 
     * @type {Array<EmployeeProfile>}
     * @memberof EmployeesProfiles
     */
    'employees'?: Array<EmployeeProfile>;
}

