/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AboutPart } from './about-part';
import { PersonalPart } from './personal-part';
import { WorkPart } from './work-part';

/**
 * 
 * @export
 * @interface EmployeeProfile
 */
export interface EmployeeProfile {
    /**
     * A unique identifier representing a specific employee.
     * @type {string}
     * @memberof EmployeeProfile
     */
    'id'?: string;
    /**
     * Employee\'s first name.
     * @type {string}
     * @memberof EmployeeProfile
     */
    'firstName'?: string;
    /**
     * Employee\'s surname.
     * @type {string}
     * @memberof EmployeeProfile
     */
    'surname'?: string;
    /**
     * Employee\'s email address.
     * @type {string}
     * @memberof EmployeeProfile
     */
    'email'?: string;
    /**
     * The employee\'s display name. This defaults to first name & last name but can be customized.
     * @type {string}
     * @memberof EmployeeProfile
     */
    'displayName'?: string;
    /**
     * 
     * @type {PersonalPart}
     * @memberof EmployeeProfile
     */
    'personal'?: PersonalPart;
    /**
     * 
     * @type {AboutPart}
     * @memberof EmployeeProfile
     */
    'about'?: AboutPart;
    /**
     * 
     * @type {WorkPart}
     * @memberof EmployeeProfile
     */
    'work'?: WorkPart;
}

