/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeDocumentWithDownloadLink } from './employee-document-with-download-link';

/**
 * 
 * @export
 * @interface EmployeeDocumentResponse
 */
export interface EmployeeDocumentResponse {
    /**
     * 
     * @type {Array<EmployeeDocumentWithDownloadLink>}
     * @memberof EmployeeDocumentResponse
     */
    'documents'?: Array<EmployeeDocumentWithDownloadLink>;
}

