/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmploymentEntryAllOf
 */
export interface EmploymentEntryAllOf {
    /**
     * Contract.
     * @type {string}
     * @memberof EmploymentEntryAllOf
     */
    'contract'?: string;
    /**
     * Type.
     * @type {string}
     * @memberof EmploymentEntryAllOf
     */
    'type'?: string;
    /**
     * Salary pay type.
     * @type {string}
     * @memberof EmploymentEntryAllOf
     */
    'salaryPayType'?: string;
    /**
     * The date this entry becomes effective.
     * @type {string}
     * @memberof EmploymentEntryAllOf
     */
    'effectiveDate'?: string;
}

