/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeTerminationNoticePeriod } from './employee-termination-notice-period';

/**
 * 
 * @export
 * @interface EmployeeTermination
 */
export interface EmployeeTermination {
    /**
     * The employee\'s termination date
     * @type {string}
     * @memberof EmployeeTermination
     */
    'terminationDate': string;
    /**
     * The ID of the \'terminationReason\' list entry
     * @type {string}
     * @memberof EmployeeTermination
     */
    'terminationReason'?: string;
    /**
     * The ID of the \'lifecycleReasonType\' list entry
     * @type {string}
     * @memberof EmployeeTermination
     */
    'reasonType'?: string;
    /**
     * 
     * @type {EmployeeTerminationNoticePeriod}
     * @memberof EmployeeTermination
     */
    'noticePeriod'?: EmployeeTerminationNoticePeriod;
    /**
     * 
     * @type {string}
     * @memberof EmployeeTermination
     */
    'lastDayOfWork'?: string;
}

