/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeDocumentWithDownloadLink
 */
export interface EmployeeDocumentWithDownloadLink {
    /**
     * The name of the document.
     * @type {string}
     * @memberof EmployeeDocumentWithDownloadLink
     */
    'documentName'?: string;
    /**
     * The name of the document.
     * @type {string}
     * @memberof EmployeeDocumentWithDownloadLink
     */
    'downloadLink'?: string;
}

