/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CurrencyValue } from './currency-value';
import { EquityEntryAllOf } from './equity-entry-all-of';
import { TableEntry } from './table-entry';

/**
 * @type EquityEntry
 * @export
 */
export type EquityEntry = EquityEntryAllOf & TableEntry;


