/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EquityEntry } from './equity-entry';

/**
 * 
 * @export
 * @interface EquityEntries
 */
export interface EquityEntries {
    /**
     * 
     * @type {Array<EquityEntry>}
     * @memberof EquityEntries
     */
    'values'?: Array<EquityEntry>;
}

