/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FieldTypeData
 */
export interface FieldTypeData {
    /**
     * The ID of the list in the /v1/company/named-lists endpoint.
     * @type {string}
     * @memberof FieldTypeData
     */
    'listId'?: string;
}

