/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FieldTypeData } from './field-type-data';

/**
 * 
 * @export
 * @interface Field
 */
export interface Field {
    /**
     * Description of the field.
     * @type {string}
     * @memberof Field
     */
    'description'?: string;
    /**
     * ID of the field.
     * @type {string}
     * @memberof Field
     */
    'id'?: string;
    /**
     * Category of the field.
     * @type {string}
     * @memberof Field
     */
    'category'?: string;
    /**
     * Name of the field.
     * @type {string}
     * @memberof Field
     */
    'name'?: string;
    /**
     * A dot-separated path of this field value in the employee JSON returned by the /v1/profiles endpoint.
     * @type {string}
     * @memberof Field
     */
    'jsonPath'?: string;
    /**
     * The type of the field. Supported field types: text, text-area, number, date, list, multi-list, hierarchy-list, currency, employee-reference, document.
     * @type {string}
     * @memberof Field
     */
    'type'?: string;
    /**
     * 
     * @type {FieldTypeData}
     * @memberof Field
     */
    'typeData'?: FieldTypeData;
    /**
     * When true, this field keeps the history of its values, each being active starting from a certain date. The default value is false.
     * @type {boolean}
     * @memberof Field
     */
    'historical'?: boolean;
}

