/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FilterInstruction } from './filter-instruction';

/**
 * 
 * @export
 * @interface GetPositionsRequest
 */
export interface GetPositionsRequest {
    /**
     * Array of field ids (paths) to fetch for the positions.<br /> Minimum 1 up to 50 fields. Any invalid number of fields will get a response of 400 HTTP error.<br /> You can include only the field ids listed in the [Positions Fields Metadata API](https://apidocs.hibob.com/reference/get_metadata-objects-position).
     * @type {Array<string>}
     * @memberof GetPositionsRequest
     */
    'fields': Array<string>;
    /**
     * 
     * @type {Array<FilterInstruction>}
     * @memberof GetPositionsRequest
     */
    'filters': Array<FilterInstruction>;
    /**
     * Whether to include the additional \"humanReadable\" entry in the response.
     * @type {boolean}
     * @memberof GetPositionsRequest
     */
    'includeHumanReadable'?: boolean;
}

