/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ImportAttendanceResponse
 */
export interface ImportAttendanceResponse {
    /**
     * Import status
     * @type {string}
     * @memberof ImportAttendanceResponse
     */
    'status'?: ImportAttendanceResponseStatusEnum;
    /**
     * Total number of clock-in and clock-out events received
     * @type {number}
     * @memberof ImportAttendanceResponse
     */
    'total'?: number;
    /**
     * Number of clock-in/clock-out events imported
     * @type {number}
     * @memberof ImportAttendanceResponse
     */
    'imported'?: number;
    /**
     * Number of clock-in/clock-out events which were not imported
     * @type {number}
     * @memberof ImportAttendanceResponse
     */
    'notImported'?: number;
    /**
     * List of all errors received in the process
     * @type {Array<string>}
     * @memberof ImportAttendanceResponse
     */
    'errors'?: Array<string>;
}

type ImportAttendanceResponseStatusEnum = 'success' | 'failed' | 'partial_success'


