/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LifeCycleEntry } from './life-cycle-entry';

/**
 * 
 * @export
 * @interface LifeCycleEntries
 */
export interface LifeCycleEntries {
    /**
     * 
     * @type {Array<LifeCycleEntry>}
     * @memberof LifeCycleEntries
     */
    'values'?: Array<LifeCycleEntry>;
}

