/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * The unique identifier of the error.
     * @type {string}
     * @memberof ModelError
     */
    'key'?: string;
    /**
     * A human readable error message.
     * @type {string}
     * @memberof ModelError
     */
    'error'?: string;
}

