/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ObjectsMetadataJsonPath
 */
export interface ObjectsMetadataJsonPath {
    /**
     * The path to the field json object. The field value and other properties, such as humanReadable value, will be placed inside.
     * @type {string}
     * @memberof ObjectsMetadataJsonPath
     */
    'root'?: string;
    /**
     * The path to the actual field value.
     * @type {string}
     * @memberof ObjectsMetadataJsonPath
     */
    'rawData'?: string;
}

