/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FieldTypeData } from './field-type-data';

/**
 * 
 * @export
 * @interface ObjectsMetadataFieldType
 */
export interface ObjectsMetadataFieldType {
    /**
     * The type of the field.
     * @type {string}
     * @memberof ObjectsMetadataFieldType
     */
    'type'?: string;
    /**
     * 
     * @type {FieldTypeData}
     * @memberof ObjectsMetadataFieldType
     */
    'typeData'?: FieldTypeData;
}

