/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjectsMetadataFieldType } from './objects-metadata-field-type';
import { ObjectsMetadataJsonPath } from './objects-metadata-json-path';

/**
 * 
 * @export
 * @interface ObjectsMetadata
 */
export interface ObjectsMetadata {
    /**
     * Description of the field.
     * @type {string}
     * @memberof ObjectsMetadata
     */
    'description'?: string;
    /**
     * ID of the field.
     * @type {string}
     * @memberof ObjectsMetadata
     */
    'id'?: string;
    /**
     * Name of the field.
     * @type {string}
     * @memberof ObjectsMetadata
     */
    'name'?: string;
    /**
     * 
     * @type {ObjectsMetadataFieldType}
     * @memberof ObjectsMetadata
     */
    'fieldType'?: ObjectsMetadataFieldType;
    /**
     * 
     * @type {ObjectsMetadataJsonPath}
     * @memberof ObjectsMetadata
     */
    'jsonPath'?: ObjectsMetadataJsonPath;
}

