/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OnboardingWizard } from './onboarding-wizard';

/**
 * 
 * @export
 * @interface OnboardingWizards
 */
export interface OnboardingWizards {
    /**
     * 
     * @type {Array<OnboardingWizard>}
     * @memberof OnboardingWizards
     */
    'wizards'?: Array<OnboardingWizard>;
}

