/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OutToday } from './out-today';

/**
 * 
 * @export
 * @interface OutTodays
 */
export interface OutTodays {
    /**
     * 
     * @type {Array<OutToday>}
     * @memberof OutTodays
     */
    'outs'?: Array<OutToday>;
}

