/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OutToday
 */
export interface OutToday {
    /**
     * Employee ID.
     * @type {string}
     * @memberof OutToday
     */
    'employeeId'?: string;
    /**
     * Employee display name.
     * @type {string}
     * @memberof OutToday
     */
    'employeeDisplayName'?: string;
    /**
     * Employee email address.
     * @type {string}
     * @memberof OutToday
     */
    'employeeEmail'?: string;
    /**
     * Display name of the policy type.
     * @type {string}
     * @memberof OutToday
     */
    'policyTypeDisplayName'?: string;
    /**
     * Date of the first day of the time off (not relevant for requests using the hours type).
     * @type {string}
     * @memberof OutToday
     */
    'startDate'?: string;
    /**
     * What portion of the first day is included - all_day, morning or afternoon (relevant for request using the days type).
     * @type {string}
     * @memberof OutToday
     */
    'startDatePortion'?: string;
    /**
     * Date of the last day of the time off (not relevant for requests using the hours type).
     * @type {string}
     * @memberof OutToday
     */
    'endDate'?: string;
    /**
     * What portion of the last day is included - all_day, morning or afternoon (relevant for request using the days type).
     * @type {string}
     * @memberof OutToday
     */
    'endDatePortion'?: string;
    /**
     * The type of request duration.<br> <b>portionOnRange</b> is when the request is for every morning or every afternoon during the days requested.<br> <b>hoursOnRange</b> is when the request is for X hours every day during the days requested.
     * @type {string}
     * @memberof OutToday
     */
    'requestRangeType'?: OutTodayRequestRangeTypeEnum;
    /**
     * What portion of the request\'s days is included - morning or afternoon (relevant for request using the portionOnRange type).
     * @type {string}
     * @memberof OutToday
     */
    'dayPortion'?: string;
    /**
     * The time off duration in hours for every request\'s days (relevant for requests with hoursOnRange type).
     * @type {number}
     * @memberof OutToday
     */
    'dailyHours'?: number;
    /**
     * Date of the time off (relevant for requests using the hours type).
     * @type {string}
     * @memberof OutToday
     */
    'date'?: string;
    /**
     * The time off duration in hours for the date (relevant for requests with hours type).
     * @type {number}
     * @memberof OutToday
     */
    'hours'?: number;
    /**
     * Relevant for requests using the hours type.
     * @type {number}
     * @memberof OutToday
     */
    'minutes'?: number;
}

type OutTodayRequestRangeTypeEnum = 'days' | 'hours' | 'portionOnRange' | 'hoursOnRange'


