/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PeopleUpdateEmployeeRecordRequestAbout
 */
export interface PeopleUpdateEmployeeRecordRequestAbout {
    /**
     * 
     * @type {Array<string>}
     * @memberof PeopleUpdateEmployeeRecordRequestAbout
     */
    'hobbies'?: Array<string>;
}

