/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PersonalPart
 */
export interface PersonalPart {
    /**
     * The employee\'s title, This can be Mr, Mrs. Ms. etc.
     * @type {string}
     * @memberof PersonalPart
     */
    'honorific'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalPart
     */
    'shortBirthDate'?: string;
    /**
     * One of Male / Female.
     * @type {string}
     * @memberof PersonalPart
     */
    'gender'?: string;
}

