/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PositionEntriesInner
 */
export interface PositionEntriesInner {
    /**
     * The position\'s full time equivalent (FTE%).
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/fte'?: any;
    /**
     * The date this position becomes effective.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/effectiveDate'?: any;
    /**
     * The position\'s employment type.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/employmentType'?: any;
    /**
     * The position\'s status.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/status'?: any;
    /**
     * The employee\'s assignment date for this position.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/actualStartDate'?: any;
    /**
     * Reason for changing or creating this position.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/reason'?: any;
    /**
     * The position\'s type.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/positionType'?: any;
    /**
     * The current assigned employee for this position.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/filledBy'?: any;
    /**
     * The position\'s job.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/job'?: any;
    /**
     * The position\'s recruitment status.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/recruitmentStatus'?: any;
    /**
     * The unique ID of this position.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/name'?: any;
    /**
     * The position\'s department.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/department'?: any;
    /**
     * The position\'s site.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/site'?: any;
    /**
     * The expected date this position should be filled.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/expectedStartDate'?: any;
    /**
     * The manager\'s position ID.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/managerPositionId'?: any;
    /**
     * The current assigned manager for this position.
     * @type {any}
     * @memberof PositionEntriesInner
     */
    '/position/managerPositionFilledBy'?: any;
}

