/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReadSingleEmployeeRequestReference
 */
export interface ReadSingleEmployeeRequestReference {
    /**
     * Optional array of employee field paths that\'s are required in response. If you don\'t specify fields - only basic fields and categories are returned: <br/><b>Basic fields:</b>  <ul>                       <li>ID</li>                       <li>Company ID</li>                       <li>Email</li>                       <li>First name</li>                       <li>Last name</li>                       <li>Display name</li>                       <li>Middle name</li>                       <li>Creation timestamp</li>                       <li>Avatar URL</li> </ul> <br/><b>Basic Categories:</b> <ul>                       <li>About</li>                       <li>Employment</li>                       <li>Work</li> </ul>
     * @type {Array<string>}
     * @memberof ReadSingleEmployeeRequestReference
     */
    'fields'?: Array<string>;
    /**
     * Optional field.  <br> <b>If not sent:</b> supply machine-readable values only. <br> <br> Possible values: <br>  <br> <b>APPEND</b> - include the additional \"humanReadable\" JSON node in the response. <br>  <br> <b>REPLACE</b> - supply humanReadable values in JSON instead of machine-readable format. <br>
     * @type {string}
     * @memberof ReadSingleEmployeeRequestReference
     */
    'humanReadable'?: string;
}

