/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Report } from './report';

/**
 * 
 * @export
 * @interface Reports
 */
export interface Reports {
    /**
     * 
     * @type {Array<Report>}
     * @memberof Reports
     */
    'views'?: Array<Report>;
}

