/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Request
 */
export interface Request {
    /**
     * 
     * @type {number}
     * @memberof Request
     */
    'requestId'?: number;
    /**
     * Employee ID.
     * @type {string}
     * @memberof Request
     */
    'employeeId'?: string;
    /**
     * Request policy type, e.g. Holiday, Sick or any defined custom type.
     * @type {string}
     * @memberof Request
     */
    'policyType'?: string;
    /**
     * Display name for the policy type. This will be translated based on the locale.
     * @type {string}
     * @memberof Request
     */
    'policyTypeDisplayName'?: string;
    /**
     * The type of request duration.<br> <b>portionOnRange</b> is when the request is for every morning or every afternoon during the days requested.<br> <b>hoursOnRange</b> is when the request is for X hours every day during the days requested.
     * @type {string}
     * @memberof Request
     */
    'type'?: RequestTypeEnum;
    /**
     * Date of the first day of the time off (not relevant for requests using the hours type).
     * @type {string}
     * @memberof Request
     */
    'startDate'?: string;
    /**
     * What portion of the first day is included - all_day, morning or afternoon (relevant for request using the days type).
     * @type {string}
     * @memberof Request
     */
    'startPortion'?: string;
    /**
     * Date of the last day of the time off (not relevant for requests using the hours type).
     * @type {string}
     * @memberof Request
     */
    'endDate'?: string;
    /**
     * What portion of the last day is included - all_day, morning or afternoon (relevant for requests using the days type).
     * @type {string}
     * @memberof Request
     */
    'endPortion'?: string;
    /**
     * What portion of the request\'s days is included - morning or afternoon (relevant for requests using the portionOnRange type).
     * @type {string}
     * @memberof Request
     */
    'dayPortion'?: string;
    /**
     * Date of the time off (relevant for request using the hours type)
     * @type {string}
     * @memberof Request
     */
    'date'?: string;
    /**
     * The time off duration in hours for the date (relevant for request using the hours type).
     * @type {number}
     * @memberof Request
     */
    'hoursOnDate'?: number;
    /**
     * Relevant for request using the hours type.
     * @type {number}
     * @memberof Request
     */
    'minutes'?: number;
    /**
     * The time off duration in hours for every day in the request (relevant for requests using the hoursOnRange type).
     * @type {number}
     * @memberof Request
     */
    'dailyHours'?: number;
    /**
     * Request status. This can be either Approved or Pending.
     * @type {string}
     * @memberof Request
     */
    'status'?: string;
    /**
     * Employee display name.
     * @type {string}
     * @memberof Request
     */
    'employeeDisplayName'?: string;
}

type RequestTypeEnum = 'days' | 'hours' | 'portionOnRange' | 'hoursOnRange'


