/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SalaryEntry } from './salary-entry';

/**
 * 
 * @export
 * @interface SalaryEntries
 */
export interface SalaryEntries {
    /**
     * 
     * @type {Array<SalaryEntry>}
     * @memberof SalaryEntries
     */
    'values'?: Array<SalaryEntry>;
}

