/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CurrencyValue } from './currency-value';

/**
 * 
 * @export
 * @interface SalaryEntryAllOf
 */
export interface SalaryEntryAllOf {
    /**
     * 
     * @type {CurrencyValue}
     * @memberof SalaryEntryAllOf
     */
    'base'?: CurrencyValue;
    /**
     * Represents the period for this salary entry. This can be one of: Annual, Hourly, Daily, Weekly, Monthly.
     * @type {string}
     * @memberof SalaryEntryAllOf
     */
    'payPeriod'?: string;
    /**
     * Represents the frequency the salary is paid. This can be one of: Weekly, Monthly, Pro rata, Every two weeks, Twice a month, Every four weeks.
     * @type {string}
     * @memberof SalaryEntryAllOf
     */
    'payFrequency'?: string;
}

