/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface StartDateUpdate
 */
export interface StartDateUpdate {
    /**
     * The date this entry becomes effective.
     * @type {string}
     * @memberof StartDateUpdate
     */
    'startDate': string;
    /**
     * Additional info for the start date update.
     * @type {string}
     * @memberof StartDateUpdate
     */
    'reason'?: string;
}

