/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SubmitTimeoffRequestDiffHoursDurationsInner } from './submit-timeoff-request-diff-hours-durations-inner';

/**
 * 
 * @export
 * @interface SubmitTimeoffRequestDiffHours
 */
export interface SubmitTimeoffRequestDiffHours {
    /**
     * Request reason.
     * @type {string}
     * @memberof SubmitTimeoffRequestDiffHours
     */
    'description'?: string;
    /**
     * Request policy type, e.g. Holiday, Sick or any custom type defined.
     * @type {string}
     * @memberof SubmitTimeoffRequestDiffHours
     */
    'policyType': string;
    /**
     * Date of the first day of the time off
     * @type {string}
     * @memberof SubmitTimeoffRequestDiffHours
     */
    'startDate': string;
    /**
     * Date of the last day of the time off.
     * @type {string}
     * @memberof SubmitTimeoffRequestDiffHours
     */
    'endDate': string;
    /**
     * Array of durations for each day in the request.
     * @type {Array<SubmitTimeoffRequestDiffHoursDurationsInner>}
     * @memberof SubmitTimeoffRequestDiffHours
     */
    'durations': Array<SubmitTimeoffRequestDiffHoursDurationsInner>;
    /**
     * Admins only can skip the approval policy. Setting this field to true will create an approved request.
     * @type {boolean}
     * @memberof SubmitTimeoffRequestDiffHours
     */
    'skipManagerApproval'?: boolean;
    /**
     * The employee ID of the user to be set as the approver for this request. This is relevant if \'skipManagerApproval\' is set to true.<br>Please note that the user calling the API with this param must have permission to import time off requests.
     * @type {string}
     * @memberof SubmitTimeoffRequestDiffHours
     */
    'approver'?: string;
    /**
     * The reason code ID taken from the policy type\'s reason codes list. The list is available in GET /timeoff/policy-types/{policyType}/reason-codes
     * @type {number}
     * @memberof SubmitTimeoffRequestDiffHours
     */
    'reasonCode'?: number;
}

