/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SubmitTimeoffRequestDiffHoursDurationsInner
 */
export interface SubmitTimeoffRequestDiffHoursDurationsInner {
    /**
     * Date of the duration.
     * @type {string}
     * @memberof SubmitTimeoffRequestDiffHoursDurationsInner
     */
    'date': string;
    /**
     * The number of hours in the duration.
     * @type {number}
     * @memberof SubmitTimeoffRequestDiffHoursDurationsInner
     */
    'hours': number;
    /**
     * The number of minutes in the duration.
     * @type {number}
     * @memberof SubmitTimeoffRequestDiffHoursDurationsInner
     */
    'minutes': number;
}

