/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Task } from './task';

/**
 * 
 * @export
 * @interface Tasks
 */
export interface Tasks {
    /**
     * 
     * @type {Array<Task>}
     * @memberof Tasks
     */
    'tasks'?: Array<Task>;
}

