/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimeoffChange } from './timeoff-change';

/**
 * 
 * @export
 * @interface TimeoffChanges
 */
export interface TimeoffChanges {
    /**
     * 
     * @type {Array<TimeoffChange>}
     * @memberof TimeoffChanges
     */
    'changes'?: Array<TimeoffChange>;
}

