/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimeoffRequestAttachmentLinksInner
 */
export interface TimeoffRequestAttachmentLinksInner {
    /**
     * 
     * @type {string}
     * @memberof TimeoffRequestAttachmentLinksInner
     */
    'filename'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeoffRequestAttachmentLinksInner
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeoffRequestAttachmentLinksInner
     */
    'mimeType'?: string;
}

