/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimeoffRequestAttachmentLinksInner } from './timeoff-request-attachment-links-inner';

/**
 * 
 * @export
 * @interface TimeoffRequest
 */
export interface TimeoffRequest {
    /**
     * The request description.
     * @type {string}
     * @memberof TimeoffRequest
     */
    'description'?: string;
    /**
     * Employee ID.
     * @type {string}
     * @memberof TimeoffRequest
     */
    'employeeId'?: string;
    /**
     * Time Off Request ID.
     * @type {number}
     * @memberof TimeoffRequest
     */
    'requestId'?: number;
    /**
     * Display name of the policy type.
     * @type {string}
     * @memberof TimeoffRequest
     */
    'policyTypeDisplayName'?: string;
    /**
     * The type of request duration.<br> <b>portionOnRange</b> is when the request is for every morning or every afternoon during the days requested.<br> <b>hoursOnRange</b> is when the request is for X hours every day during the days requested.
     * @type {string}
     * @memberof TimeoffRequest
     */
    'type'?: TimeoffRequestTypeEnum;
    /**
     * Date of the first day of the time off  (not relevant for requests using the hours type).
     * @type {string}
     * @memberof TimeoffRequest
     */
    'startDate'?: string;
    /**
     * What portion of the first day is included - all_day, morning or afternoon (relevant for requests using the Days type).
     * @type {string}
     * @memberof TimeoffRequest
     */
    'startDatePortion'?: string;
    /**
     * Date of the last day of the time off (not relevant for requests using                                                the hours type).
     * @type {string}
     * @memberof TimeoffRequest
     */
    'endDate'?: string;
    /**
     * What portion of the last day is included - all_day, morning or afternoon (relevant for requests using the Days type).
     * @type {string}
     * @memberof TimeoffRequest
     */
    'endDatePortion'?: string;
    /**
     * What portion of the request\'s days is included - morning or afternoon (relevant for requests using the portionOnRange type).
     * @type {string}
     * @memberof TimeoffRequest
     */
    'dayPortion'?: string;
    /**
     * Whether the request is approved (and hence publicly visible).
     * @type {boolean}
     * @memberof TimeoffRequest
     */
    'approved'?: boolean;
    /**
     * Date of the time off (relevant for requests using the Hours type).
     * @type {string}
     * @memberof TimeoffRequest
     */
    'date'?: string;
    /**
     * The time off duration in hours for the date (relevant for requests using the Hours type)
     * @type {number}
     * @memberof TimeoffRequest
     */
    'hoursOnDate'?: number;
    /**
     * The time off duration in hours for every day in the request (relevant for requests using the hoursOnRange type).
     * @type {number}
     * @memberof TimeoffRequest
     */
    'dailyHours'?: number;
    /**
     * The unit used for the totalDuration and totalCost - either \'days\' or \'hours\'
     * @type {string}
     * @memberof TimeoffRequest
     */
    'durationUnit'?: TimeoffRequestDurationUnitEnum;
    /**
     * The total amount of time the request covers, including regular days off such as weekends
     * @type {number}
     * @memberof TimeoffRequest
     */
    'totalDuration'?: number;
    /**
     * The amount that will be deducted from the balance
     * @type {number}
     * @memberof TimeoffRequest
     */
    'totalCost'?: number;
    /**
     * Request status. This can be approved, pending, canceled, etc.
     * @type {string}
     * @memberof TimeoffRequest
     */
    'status'?: string;
    /**
     * Whether the request has attachments
     * @type {boolean}
     * @memberof TimeoffRequest
     */
    'hasAttachment'?: boolean;
    /**
     * The reason code taken from the policy type\'s reason codes list. The list is available in GET /timeoff/policy-types/{policyType}/reason-codes
     * @type {string}
     * @memberof TimeoffRequest
     */
    'reasonCode'?: string;
    /**
     * Attachments with download links
     * @type {Array<TimeoffRequestAttachmentLinksInner>}
     * @memberof TimeoffRequest
     */
    'attachmentLinks'?: Array<TimeoffRequestAttachmentLinksInner>;
}

type TimeoffRequestTypeEnum = 'days' | 'hours' | 'portionOnRange' | 'hoursOnRange'
type TimeoffRequestDurationUnitEnum = 'days' | 'hours'


