/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TrainingEntry } from './training-entry';

/**
 * 
 * @export
 * @interface TrainingEntries
 */
export interface TrainingEntries {
    /**
     * 
     * @type {Array<TrainingEntry>}
     * @memberof TrainingEntries
     */
    'values'?: Array<TrainingEntry>;
}

