/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CurrencyValue } from './currency-value';
import { TableEntry } from './table-entry';
import { TrainingEntryAllOf } from './training-entry-all-of';

/**
 * @type TrainingEntry
 * @export
 */
export type TrainingEntry = TableEntry & TrainingEntryAllOf;


