/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CurrencyValue } from './currency-value';

/**
 * 
 * @export
 * @interface TrainingEntryAllOf
 */
export interface TrainingEntryAllOf {
    /**
     * Further description about the training entry.
     * @type {string}
     * @memberof TrainingEntryAllOf
     */
    'description'?: string;
    /**
     * The name of the training entry. The name must be an item in the training list field.
     * @type {string}
     * @memberof TrainingEntryAllOf
     */
    'name'?: string;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof TrainingEntryAllOf
     */
    'cost'?: CurrencyValue;
    /**
     * The status of the training entry
     * @type {string}
     * @memberof TrainingEntryAllOf
     */
    'status'?: string;
    /**
     * The frequency of the training entry. The name must be of an item in the frequency list field.
     * @type {string}
     * @memberof TrainingEntryAllOf
     */
    'frequency'?: string;
    /**
     * The date this entry becomes effective.
     * @type {string}
     * @memberof TrainingEntryAllOf
     */
    'startDate'?: string;
    /**
     * The date of training completion.
     * @type {string}
     * @memberof TrainingEntryAllOf
     */
    'endDate'?: string;
    /**
     * ID of the document attached to this training entry.
     * @type {number}
     * @memberof TrainingEntryAllOf
     */
    'documentId'?: number;
}

