/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UpdateListItemRequest
 */
export interface UpdateListItemRequest {
    /**
     * Name of the item.
     * @type {string}
     * @memberof UpdateListItemRequest
     */
    'name'?: string;
    /**
     * ID of the new hierarchy parent node.
     * @type {number}
     * @memberof UpdateListItemRequest
     */
    'parentId'?: number;
}

