/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UpdateFieldRequest
 */
export interface UpdateFieldRequest {
    /**
     * The description of the field.
     * @type {string}
     * @memberof UpdateFieldRequest
     */
    'description'?: string;
    /**
     * The name of the field.
     * @type {string}
     * @memberof UpdateFieldRequest
     */
    'name'?: string;
}

