/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UploadAvatar
 */
export interface UploadAvatar {
    /**
     * The URL of the source of the avatar image.
     * @type {string}
     * @memberof UploadAvatar
     */
    'url': string;
}

