/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CurrencyValue } from './currency-value';

/**
 * 
 * @export
 * @interface VariableEntryAllOf
 */
export interface VariableEntryAllOf {
    /**
     * 
     * @type {CurrencyValue}
     * @memberof VariableEntryAllOf
     */
    'amount'?: CurrencyValue;
    /**
     * The type of variable pay.
     * @type {string}
     * @memberof VariableEntryAllOf
     */
    'variableType'?: string;
    /**
     * This represents the period for this variable entry. It can be one of: Annual, Half-Yearly, Quarterly, Monthly.
     * @type {string}
     * @memberof VariableEntryAllOf
     */
    'paymentPeriod'?: string;
    /**
     * The employee\'s company on-target weight, in percent.
     * @type {number}
     * @memberof VariableEntryAllOf
     */
    'companyPercent'?: number;
    /**
     * The employee\'s department on-target weight, in percent.
     * @type {number}
     * @memberof VariableEntryAllOf
     */
    'departmentPercent'?: number;
    /**
     * The employee\'s individual on-target weight, in percent.
     * @type {number}
     * @memberof VariableEntryAllOf
     */
    'individualPercent'?: number;
}

