/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TableEntry } from './table-entry';
import { WorkEntryAllOf } from './work-entry-all-of';
import { WorkEntryAllOfReportsTo } from './work-entry-all-of-reports-to';

/**
 * @type WorkEntry
 * @export
 */
export type WorkEntry = TableEntry & WorkEntryAllOf;


