/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkEntryAllOfReportsTo } from './work-entry-all-of-reports-to';

/**
 * 
 * @export
 * @interface WorkEntryAllOf
 */
export interface WorkEntryAllOf {
    /**
     * The employee\'s job title.
     * @type {string}
     * @memberof WorkEntryAllOf
     */
    'title'?: string;
    /**
     * The employee\'s department.
     * @type {string}
     * @memberof WorkEntryAllOf
     */
    'department'?: string;
    /**
     * The employee\'s site.
     * @type {string}
     * @memberof WorkEntryAllOf
     */
    'site'?: string;
    /**
     * The employee\'s site ID.
     * @type {number}
     * @memberof WorkEntryAllOf
     */
    'siteId'?: number;
    /**
     * 
     * @type {WorkEntryAllOfReportsTo}
     * @memberof WorkEntryAllOf
     */
    'reportsTo'?: WorkEntryAllOfReportsTo;
    /**
     * The date this entry becomes effective.
     * @type {string}
     * @memberof WorkEntryAllOf
     */
    'effectiveDate'?: string;
    /**
     * 
     * @type {object}
     * @memberof WorkEntryAllOf
     */
    'customColumns'?: object;
}

