/*
Bob API

Access your employees data with the Bob API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkEntry } from './work-entry';

/**
 * 
 * @export
 * @interface WorkEntries
 */
export interface WorkEntries {
    /**
     * 
     * @type {Array<WorkEntry>}
     * @memberof WorkEntries
     */
    'values'?: Array<WorkEntry>;
}

